### PR TITLE
Work around live streams

### PR DESCRIPTION
**Pull request by Kuci**
For more information, see 89ea8dae891d9ed3ba7ae3e28aa3d052cbd0f162 commit message.

### CODE REVIEW

**Comment by mx3L** [comment]
Hi, didn't checked here until I updated plugin. Can you please update your patch for reworked addon?

**Comment by Kuci** [comment]
Sure, will do it ASAP.

**Comment by Kuci** [comment]
Here you go.

**Comment by mx3L** [comment]
Thanks!

**Pull request merged**
